In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
#actually this one hot encoding works in hashing format it means , it word is given a specific index or mailbox 

In [5]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6641, 6830, 5694, 1176],
 [6641, 6830, 5694, 3300],
 [6641, 3292, 5694, 868],
 [7601, 7670, 1962, 1159, 8027],
 [7601, 7670, 1962, 1159, 4333],
 [4079, 6641, 8949, 5694, 7857],
 [1805, 2063, 3785, 1159]]

In [7]:
##Word embedding 
from tensorflow.keras.layers import Embedding

#pad sequunecs used to convert evry vector to same length so that it can processed further in matrix format 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np
sent_length=8
#pre padding means in starting 0 will add 
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6641 6830 5694 1176]
 [   0    0    0    0 6641 6830 5694 3300]
 [   0    0    0    0 6641 3292 5694  868]
 [   0    0    0 7601 7670 1962 1159 8027]
 [   0    0    0 7601 7670 1962 1159 4333]
 [   0    0    0 4079 6641 8949 5694 7857]
 [   0    0    0    0 1805 2063 3785 1159]]


In [16]:
#feature representation 
voc_size = 10000
dim = 10
sent_length = 8

model = Sequential()
# By adding input_length, Keras can calculate the shapes immediately
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')
model.summary()
#model.compile will configures the training process of the neural network , this will tell two
#main things 1. how to update weights 2. How to measure error 
#adam - optimizer adam(Adaptive Moment Estimation)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
voc_size = 10000
dim = 10
sent_length = 8

model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

# --- THE FIX ---
# Create a "Dummy" input: 1 sequence of 8 zeros
# This forces Keras to 'Build' the internal weight matrix
dummy_data = np.zeros((1, sent_length))
model.predict(dummy_data, verbose=0)

# Now check the summary
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step


array([[[ 0.04369792,  0.00293633, -0.0048349 ,  0.04141853,
         -0.03940365, -0.0474535 ,  0.03661689, -0.02309321,
         -0.02931641, -0.0097198 ],
        [ 0.04369792,  0.00293633, -0.0048349 ,  0.04141853,
         -0.03940365, -0.0474535 ,  0.03661689, -0.02309321,
         -0.02931641, -0.0097198 ],
        [ 0.04369792,  0.00293633, -0.0048349 ,  0.04141853,
         -0.03940365, -0.0474535 ,  0.03661689, -0.02309321,
         -0.02931641, -0.0097198 ],
        [ 0.04369792,  0.00293633, -0.0048349 ,  0.04141853,
         -0.03940365, -0.0474535 ,  0.03661689, -0.02309321,
         -0.02931641, -0.0097198 ],
        [ 0.04463794, -0.00334119,  0.0289529 , -0.01918738,
         -0.00807496,  0.00153515, -0.01511826, -0.03711956,
          0.00347481, -0.00472254],
        [ 0.04512772, -0.02448665, -0.03650712,  0.0308787 ,
          0.0455674 , -0.01021541,  0.03628674,  0.02802796,
          0.02384194, -0.02992485],
        [-0.01551161, -0.0046898 ,  0.01247402,  0.0